### PR TITLE
exclude pan cancer core genes by default in cell model page

### PR DESCRIPTION
**Pull request by emepyc**

### CODE REVIEW

**Review by Donnyvdm — CHANGES_REQUESTED** [review]
Essentially it works, but I would like that excludePanCancerGenes parameter is 1 by default and only if it's explicitly set to false (or 0) the pancancer genes will be showed.
In other words, if I go to /model/<model_id>, the pancancer genes should be hidden.
There are some external links to project score that might not be aware of this parameter and simply link to /model/<model_id>, and I'd like those to show the limited dataset as well.

**Comment by emepyc** [comment]
sounds reasonable. Thanks for the feedback

**Comment by emepyc** [comment]
@Donnyvdm, I think this small change is closer to what you expected?

**Review by Donnyvdm — APPROVED** [review]

**Comment by Donnyvdm** [comment]
Yes, that's it :)

**Pull request merged**
