### PR TITLE
Cancer types data filter

### LINKED ISSUE #13: substitute home tissues plot for cancer types (analyses) plot

### LINKED ISSUE #14: use cancer types instead of tissues in data filter

### LINKED ISSUE #15: search by cancer types instead of tissues
Currently the user can search by tissue. When a tissue is selected the data page with a tissue filter is set. Since we are no going to use tissue filters but cancer type filters we need to change the behaviour of the searchbox.

### PR DESCRIPTION
**Pull request by emepyc**
I think I need to use `analyses` instead of `cancerTypes` in most parts of the code.

Fixes #13 
Fixes #14 
Fixes #15

### CODE REVIEW

**Comment by emepyc** [comment]
Fixes #9

**Comment by emepyc** [comment]
@Donnyvdm I've now used `analyses` in most of the places where I was using `cancerTypes`. I think this is consistent now.
If you can take a look that would be great, otherwise I'll merge shortly, since some changes here conflicts with other PRs and next work on priority scores.

**Review by Donnyvdm — APPROVED** [review]
Looks good to me, but I haven't checked it with the rest of the team. Feel free to merge - we can always rename a label if we get strong feedback that the name 'analysis' is not as obvious as 'cancer type'.

**Comment by emepyc** [comment]
Yes, I still finds it confusing to have analysis and cancer types so closely related.
Also because for the same _name_ you have an analysis id and cancer type id that are different.
My main concern is not to confuse the users

**Comment by Donnyvdm** [comment]
Yes, basically if there were enough cell lines of a specific `cancer type` CRISPR screened, an `analysis` was performed on that set of models. But it does make it tricky which term to use where. Once this is merged I'll deploy it to our internal staging site and ask for feedback from the team.

**Comment by emepyc** [comment]
Thanks Donny, This is now merged. Please let me know what feedback you get.

**Pull request merged**
