### PR TITLE
show genes and models without "available" status as disabled options …

### LINKED ISSUE #6: Include genes without essentiality scores in the search
Users have reported that they are not able to find their preferred gene in the search box. This is happening because not all genes have essentiality scores and the search only works for them.
The search box should display any gene (irrespective of data in the project score). Those that don't have essentiality scores should appear greyed out with a short explanation of why it is not clickable ("No essentiality scores"?)

### PR DESCRIPTION
**Pull request by emepyc**
…in search box

Fixes #6

### CODE REVIEW

**Comment by Donnyvdm** [comment]
Essentially it works well, but I think we should provide more information in the search results explaining why a gene is greyed-out. Particularly the difference between 'never essential' and 'not screened' is important for people to know. For instance, the 'never essential'-genes do have results in the raw data files.
What do you think?

**Comment by emepyc** [comment]
Fine by me. I can add the explanation to the search option

**Comment by emepyc** [comment]
@Donnyvdm, I think this should make it...

Screenshot 2019-08-20 at 01 49 09

**Review by Donnyvdm — APPROVED** [review]
That's great Miguel, go ahead and merge it

**Comment by emepyc** [comment]
On smaller screens, the search box in the navigation bar displays the genes correctly:

Screenshot 2019-08-20 at 02 15 33

But models look a bit misaligned though.

Screenshot 2019-08-20 at 02 15 52

I may try to fix that a bit. What do you think?

**Comment by Donnyvdm** [comment]
Actually, after using it a little more, I think we should hide the 'not screened' models. I added them for completeness, but actually it doesn't make much sense.
For the genes, it is very useful for people to know what was screened, but for the models it doesn't add anything. 
I'll go ahead and remove them from the search results (so the counts are correct too) and we won't have to worry about this layout issue either.

**Comment by emepyc** [comment]
Thanks Donny. I'll change the code accordingly

**Comment by emepyc** [comment]
Hi Donny, the code assumes that...
- You will remove the models without `available` status from the search results
- The search response for the models will still have a `status` attribute that is (always) set to `available`.
If that's the case I'll go ahead and merge. Otherwise let me know and I'll change the code accordingly.

**Comment by Donnyvdm** [comment]
Hi Miguel, yes your assumptions were correct and this is now implemented in the search results. I think this can be merged and closed now.

**Comment by emepyc** [comment]
Thanks!

**Pull request merged**
